#!/bin/sh

arq=`echo $1 | sed s/"\.tex"//g`

latex $arq.tex

bibtex $arq.aux

makeindex $arq.idx

latex $arq.tex

latex $arq.tex

# gera arquivo postscript
#dvips -o $arq.ps $arq.dvi

dvipdft $arq.dvi

exec evince $arq.pdf & > /dev/null
