#!/bin/sh

latex Monografia.tex

bibtex Monografia.aux

makeindex Monografia.ind

latex Monografia.tex

latex Monografia.tex

dvipdft Monografia.dvi

rm -fr *.aux *.bbl *.blg *.dvi *.dvi *.log *.log *.lot *.toc *.lof

evince Monografia.pdf & > /dev/null
