#!/bin/sh

latex Monografia.tex

bibtex Monografia.aux

makeindex Monografia.ind

latex Monografia.tex

latex Monografia.tex

dvipdft Monografia.dvi

rm -fr *.aux,*.log,*.bbl,*.blg,*.lot,*.toc,*.lob,*.lof

evince Monografia.pdf & > /dev/null
